# ==========================
# REPORT GENERATOR
# ==========================

def generate_report(
    ats_score,
    resume_skills,
    missing_skills,
    job_role,
    gaps,
    roadmap,
    projects,
    interview_questions
):

    report = f"""
==========================================
          AI CAREER COPILOT REPORT
==========================================

ATS SCORE
----------
{ats_score} %

TARGET ROLE
-----------
{job_role}

SKILLS FOUND
------------
{', '.join(resume_skills)}

MISSING SKILLS
--------------
{', '.join(missing_skills)}

==========================================
SKILL GAP ANALYSIS
==========================================

"""

    if gaps:

        for skill in gaps:

            report += f"• {skill}\n"

    else:

        report += "No Skill Gaps Found\n"

    report += """

==========================================
LEARNING ROADMAP
==========================================

"""

    for item in roadmap:

        report += f"• {item}\n"

    report += """

==========================================
RECOMMENDED PROJECTS
==========================================

"""

    for project in projects:

        report += f"• {project}\n"

    report += """

==========================================
INTERVIEW QUESTIONS
==========================================

"""

    for question in interview_questions:

        report += f"• {question}\n"

    report += """

==========================================
Generated by AI Career Copilot

Created by Shruti Singh
==========================================

"""

    return report